version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  integrador-commands:
    volumes:
        - ./integrador/:/mnt/
    build: ./integrador
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis
  reporte_consolidado_paciente-queries:
    volumes:
        - ./reporte_consolidado_paciente/:/mnt/
    build: ./reporte_consolidado_paciente
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on: 
      - redis
  reporte_consolidado_paciente-commands:
    volumes:
        - ./reporte_consolidado_paciente/:/mnt/
    build: ./reporte_consolidado_paciente
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis  
  worker-reporte_consolidado_paciente:
    volumes:
      - ./reporte_consolidado_paciente/:/mnt/
    build: ./reporte_consolidado_paciente
    working_dir: /backend/
    command: rq worker -u 'redis://redis/0'
    depends_on:
      - redis  
  pago-commands:
    volumes:
        - ./pago/:/mnt/
    build: ./pago
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis

  calculador-commands:
    volumes:
        - ./calculador/:/mnt/
    build: ./calculador
    working_dir: /backend/
    command: sh run_commands.sh
    depends_on: 
      - redis 

  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - integrador-commands
        - reporte_consolidado_paciente-queries
        - reporte_consolidado_paciente-commands
        - worker-reporte_consolidado_paciente
        - pago-commands
