version: "3.2"
services:
  redis:
    image: redis
    #volumes: 
    #  - ./data:/data
  integrador-commands:
    volumes:
        - ./integrador/:/backend/
    build: ./integrador
    working_dir: /backend/
    command: sh run_commands.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis
  reporte_consolidado_paciente-queries:
    volumes:
        - ./reporte_consolidado_paciente/:/backend/
    build: ./reporte_consolidado_paciente
    working_dir: /backend/
    command: sh run_queries.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis
  reporte_consolidado_paciente-commands:
    volumes:
        - ./reporte_consolidado_paciente/:/backend/
    build: ./reporte_consolidado_paciente
    working_dir: /backend/
    command: sh run_commands.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis  
  worker-reporte_consolidado_paciente:
    volumes:
      - ./reporte_consolidado_paciente/:/backend/
    build: ./reporte_consolidado_paciente
    working_dir: /backend/
    command: rq worker -u 'redis://redis/0'
    env_file:
      - common.env
      - secrets.env
    depends_on:
      - redis  
  pago-commands:
    volumes:
        - ./pago/:/backend/
    build: ./pago
    working_dir: /backend/
    command: sh run_commands.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis
  calculador-commands:
    volumes:
        - ./calculador/:/backend/
    build: ./calculador
    working_dir: /backend/
    command: sh run_commands.sh
    env_file:
      - common.env
      - secrets.env
    depends_on:
      - redis
  clinical_history-commands:
    volumes:
        - ./history/:/backend/
    build: ./history
    working_dir: /backend/
    command: sh run_commands.sh
    env_file:
      - common.env
      - secrets.env
    depends_on:
      - redis
  clinical_history-queries:
    volumes:
        - ./history/:/backend/
    build: ./history
    working_dir: /backend/
    command: sh run_queries.sh
    env_file:
      - common.env
      - secrets.env
    depends_on:
      - redis
  reporte_financiero-queries:
    volumes:
        - ./reporte_financiero/:/backend/
    build: ./reporte_financiero
    working_dir: /backend/
    command: sh run_queries.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis
      - jwt-queries
      - acl-queries
  reporte_financiero-commands:
    volumes:
        - ./reporte_financiero/:/backend/
    build: ./reporte_financiero
    working_dir: /backend/
    command: sh run_commands.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis  
      - jwt-queries
      - acl-queries
  worker-reporte_financiero_paciente:
    volumes:
      - ./reporte_financiero/:/backend/
    build: ./reporte_financiero
    working_dir: /backend/
    command: rq worker -u 'redis://redis/1'
    env_file:
      - common.env
      - secrets.env
    depends_on:
      - redis
      - jwt-queries
      - acl-queries
  jwt-queries:
    volumes:
        - ./jwt/:/backend/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh
    env_file:
      - common.env
      - secrets.env
    depends_on: 
      - redis
  acl-queries:
    volumes:
        - ./acl/:/backend/
    build: ./acl
    working_dir: /backend/
    command: sh run.sh
    env_file:
      - common.env
      - secrets.env
  monitor:
    volumes:
      - ./monitor:/backend
    working_dir: /backend/
    build: ./monitor
    command: sh run.sh
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - 5000:443
    volumes:
        - ./reporte_financiero/static:/var/www/reporte_financiero/static
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
        - integrador-commands
        - reporte_consolidado_paciente-queries
        - reporte_consolidado_paciente-commands
        - worker-reporte_consolidado_paciente
        - pago-commands
        - reporte_financiero-queries
        - reporte_financiero-commands
        - jwt-queries
        - acl-queries
